service: miranda-backend
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:

  name: aws
  region: eu-west-3
  stage: ${opt:stage, 'dev'}  # Default to 'dev' stage if not specified
  deploymentBucket: 
    name: miranda-backend
  environment:
    NODE_ENV: production
    SECRET_KEY: ${file(.env.json):SECRET_KEY}
    MONGO_DB_URI: ${file(.env.json):MONGO_DB_URI}
    STATIC_FILES_BASE_URL: ${file(.env.json):STATIC_FILES_BASE_URL}
    CLIENT_BASE_URL: ${file(.env.json):CLIENT_BASE_URL}
    STAGE: ${opt:stage, 'dev'}
  runtime: nodejs20.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
