name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Build project
      run: npm run build
    - name: Set up environment variables
      run: |
        echo '{' > .env.json
        echo '"SECRET_KEY": "${{ secrets.SECRET_KEY }}",' >> .env.json
        echo '"MONGO_DB_URI": "${{ secrets.MONGO_DB_URI }}",' >> .env.json
        echo '"STATIC_FILES_BASE_URL": "${{ secrets.STATIC_FILES_BASE_URL }}",' >> .env.json
        echo '"CLIENT_BASE_URL": "${{ secrets.CLIENT_BASE_URL }}"' >> .env.json
        echo '}' >> .env.json
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
